version: "3.8"
services:
  gradle:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.dev
    command: ["tail", "-f", "/dev/null"]
    env_file: .env
    volumes:
      - ./app:/usr/src/template
      - ./build.sh:/usr/src/template/build.sh
